services:
  ghost:
    image: ghost:5
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: sqlite3
      database__connection__filename: content/data/ghost.db
      url: http://localhost:2368
    volumes:
      - ghost_content:/var/lib/ghost/content

volumes:
  ghost_content:
